name: Deploy ke GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload halaman
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2